name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Passo inicial
      run: echo "Passo inicial!"

    - name: Segundo passo
      run: echo "Segundo passo!"

    - name: Passo final
      run: echo "Passo inicial!"
  
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Passo inicial
      run: echo "Passo inicial!"

    - name: Segundo passo
      run: echo "Segundo passo!"

    - name: Passo final
      run: echo "Passo inicial!"
