name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Passo inicial
      run: |
        echo "Passo inicial!"
        sleep 10

    - name: Segundo passo
      run: |
        echo "Segundo passo!"
        sleep 10

    - name: Passo final
      run: |
        echo "Passo final!"
        sleep 10
  
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
          
    - name: Passo inicial
      run: |
        echo "Passo inicial!"
        sleep 20

    - name: Segundo passo
      run: |
        echo "Segundo passo!"
        sleep 20

    - name: Passo final
      run: |
        echo "Passo final!"
        sleep 20
